### ISSUE TITLE
need wireframe images

### ISSUE THREAD

**Issue by Tirzahe** [Tirzahe/Group-Tour#7]
<img width="1197" alt="screen shot 2018-05-09 at 12 10 45 am" src="https://user-images.githubusercontent.com/16514603/39798386-97ad7766-531d-11e8-8c94-89827c4bb3a0.png">
<img width="1213" alt="screen shot 2018-05-09 at 12 07 38 am" src="https://user-images.githubusercontent.com/16514603/39798303-34be4ad6-531d-11e8-9859-56803ec019be.png">
<img width="1207" alt="screen shot 2018-05-09 at 12 08 10 am" src="https://user-images.githubusercontent.com/16514603/39798305-36befa06-531d-11e8-9ee0-fc4f4e60fdb0.png">
<img width="1211" alt="screen shot 2018-05-09 at 12 08 29 am" src="https://user-images.githubusercontent.com/16514603/39798309-388a324c-531d-11e8-8830-b3ea9696a7dc.png">

**Comment by Tirzahe** [comment]
now we need traveler profile page, trip collaboration page, activity add/edit page,

**Comment by lelanavilla** [comment]
<img width="1440" alt="screen shot 2018-05-09 at 6 30 00 pm" src="https://user-images.githubusercontent.com/31450076/39846553-83e85eca-53b9-11e8-8368-198f41156060.png">
<img width="1440" alt="screen shot 2018-05-09 at 6 46 15 pm" src="https://user-images.githubusercontent.com/31450076/39846563-94b65d10-53b9-11e8-93c3-5496ab00b036.png">

**Comment by lelanavilla** [comment]
basic wireframe with general idea of layout of the main group page and explore destinations page
